# Generated by Django 5.2.15 on 2026-06-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short uppercase org code used in ticket references, e.g. GMEC.', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client organisation this user belongs to; null for internal staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.client'),
        ),
    ]
