"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load DB_* (and any future) credentials from a root .env file. The file is
# gitignored; secrets never live in this (tracked) settings module.
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    """Read a boolean from the environment (1/true/yes/on → True)."""
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    """Read a comma-separated list from the environment (blank → [])."""
    return [item.strip() for item in os.getenv(name, '').split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: read from the environment in every real deployment. The
# clearly-insecure fallback only keeps local dev running out of the box and must
# never be used when DEBUG is off (see the production-hardening block below).
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or (
    'django-insecure-p-vf__8)9)f2=qph!8&xo4+-f&*1!m92%v0psqz&+#!ys59i+#'
)

# DEBUG defaults to True for local dev convenience; set DJANGO_DEBUG=False in any
# non-local environment.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# Comma-separated hosts via DJANGO_ALLOWED_HOSTS. When DEBUG is on and none are
# given, fall back to the usual loopback names so runserver works out of the box.
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Origins trusted for CSRF (scheme required, e.g. https://tweedle.example.com).
# Required once the app is served over HTTPS behind a domain.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',          # required by allauth

    # Authentication (Phase 3a) — local username/email + password only.
    'allauth',
    'allauth.account',

    # Project apps
    'accounts',          # custom user + identity
    'core',              # shared/base
    'tickets',           # Ticket, TicketEvent, transition engine (Phase 2)
    'notifications',     # in-app notifications (Phase 2)
    'admin_portal',
    'client_portal',
    'subuser_portal',
    'developer_portal',
    'tester_portal',
]

# Custom user model — MUST be set before the first migration so the very
# first migrate runs with accounts.CustomUser already active.
AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files in production. Must sit directly
    # below SecurityMiddleware and above everything else. No-op in local dev
    # (runserver still serves static itself).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # required by allauth
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Use the existing static-frontend templates folder. These are NOT
        # converted to Django syntax yet (Phase 4); registered now so the
        # loader can find them.
        'DIRS': [BASE_DIR / 'Tweedle' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Driven by the .env file. Set DB_ENGINE=postgresql to use PostgreSQL (built
# from the DB_* vars); with no .env / any other value it falls back to the
# zero-config SQLite db.sqlite3, so the project still runs out of the box.
if os.getenv('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'tweedle'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── Authentication (Phase 3a: django-allauth, minimal) ──────────────────────
# Local username/email + password only: no email verification, no social
# providers, no MFA (deferred). Public self-registration is CLOSED — this is an
# admin-provisioned product (see core.adapters.NoSignupAccountAdapter).
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# New-style allauth settings (allauth 65+).
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_ADAPTER = 'core.adapters.NoSignupAccountAdapter'
# Let the login page's "Keep me signed in" checkbox control session length.
ACCOUNT_SESSION_REMEMBER = None

# Email: real SMTP when DJANGO_EMAIL_HOST is set, otherwise the console backend
# (prints emails to the terminal) so local dev needs no mail server. In-app
# notifications also trigger emails via notifications/signals.py.
if os.getenv('DJANGO_EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = _env_bool('DJANGO_EMAIL_USE_TLS', True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'Tweedle <no-reply@tweedle.local>')

# Absolute base URL used to build links in outgoing emails (no trailing slash).
BASE_URL = os.getenv('DJANGO_BASE_URL', '').rstrip('/')

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'post_login_redirect'
LOGOUT_REDIRECT_URL = 'account_login'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Serve the existing static-frontend assets (css/images/js) during dev.
STATICFILES_DIRS = [BASE_DIR / 'Tweedle' / 'static']

# Destination for `python manage.py collectstatic` — the directory WhiteNoise
# (or a web server / CDN) serves from. Gitignored. Not used in DEBUG.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static-files storage: WhiteNoise's compression backend gzips/brotlis the
# collected assets at `collectstatic` time. We use the *non-manifest* variant
# (no hashed filenames) so `{% static %}` resolves without a manifest — which
# keeps the test suite green and collectstatic resilient to the legacy
# frontend's asset references. Upgrade to CompressedManifestStaticFilesStorage
# at deploy time (cache-busting hashes) once collectstatic runs clean.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files (user uploads — e.g. ticket attachments).
# In production these must be served by the web server / object storage; the
# DEBUG-only urlpattern in config/urls.py handles local dev. (See P0 deploy item.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Production security hardening ───────────────────────────────────────────
# Only applied when DEBUG is off, so local HTTP development is unaffected. These
# assume the app is served over HTTPS (directly or behind a TLS-terminating
# reverse proxy / load balancer). See the deployment checklist:
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
if not DEBUG:
    # Refuse to boot with the throwaway dev secret in a real environment.
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set (the insecure dev fallback cannot be '
            'used when DEBUG is off).'
        )

    # Redirect HTTP → HTTPS and trust the proxy's X-Forwarded-Proto header so the
    # redirect/secure-cookie logic works behind a TLS-terminating proxy.
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Only send session/CSRF cookies over HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security (default 1 year; override via env).
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Misc hardening.
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ── Tweedle domain constants ────────────────────────────────────────────────
# After this many days a closed ticket can no longer be reopened by the client
# (admins may reopen anytime). See TARGET_TICKET_FLOW.md §4 (T11).
REOPEN_WINDOW_DAYS = 14

# A resolved ticket with no client action is auto-closed after this many days by
# the `close_stale_resolved` management command (run on a schedule). TARGET §9.
AUTO_CLOSE_DAYS = 7
