# Generated by Django 5.2.15 on 2026-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Tweedle Demo Org', max_length=200)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('default_priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('powered_by_tweedle', models.BooleanField(default=True)),
                ('notification_prefs', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation settings',
                'verbose_name_plural': 'Organisation settings',
            },
        ),
    ]
