# Generated by Django 5.2.15 on 2026-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='kind',
            field=models.CharField(choices=[('message', 'Message'), ('info_request', 'Information Request')], default='message', max_length=20),
        ),
    ]
