# Generated by Django 5.2.15 on 2026-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_backfill_sla_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
